openapi: 3.0.3
info:
  title: External Provider Swagger
  description: |-
    Документация API модуля взаимодействия с 1С
  version: 1.0.0
tags:
  - name: External
    description: External provider

security:
  - OAuth2_Local: [ ]
  - OAuth2_Integration: [ ]
paths:
  /external/{number}:
    post:
      tags:
        - External
      summary: Post change number of products from external service
      description: Change number of products from external service
      operationId: ChangeProductNumberByPost
      security:
        - OAuth2_Local: [ ]
        - OAuth2_Integration: [ ]
      parameters:
        - $ref: '#/components/parameters/NumberQuery'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad Request/Internal Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    OAuth2_Local:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://localhost:8444/realms/local/protocol/openid-connect/token
          scopes: { }

    OAuth2_Integration:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://adrontest.com:9443/realms/adron-test/protocol/openid-connect/token
          scopes: { }

  parameters:
    NumberQuery:
      in: path
      name: number
      required: true
      description: Number of products
      example: 300
      schema:
        type: number

  schemas:
    ErrorResponse:
      type: object
      required:
        - errorCode
        - message
        - detailedMessage
        - timestamp
      description: Controlled Error Response
      properties:
        errorCode:
          type: string
          description: Error Business Code
          example: AGS-08
        message:
          type: string
          description: Error Description
          example: Old password doesn't match
        timestamp:
          type: string
          description: When the controlled error was produced
          example: 2024-04-21T13:26:44.148
        args:
          type: object
          description: Dynamic parameters passes as Map<String, Any>
